FROM node:20-alpine AS base
RUN corepack enable

FROM base AS builder
WORKDIR /app
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY packages/shared/ packages/shared/
COPY packages/backend/ packages/backend/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm --filter @remotehub/shared build
RUN pnpm --filter @remotehub/backend build
RUN npx esbuild packages/backend/prisma/seed.ts --outfile=packages/backend/prisma/seed.js --platform=node --format=cjs --bundle
RUN pnpm --filter @remotehub/backend --prod deploy /prod/backend
RUN cp -r packages/backend/dist /prod/backend/dist
RUN cp -r packages/backend/prisma /prod/backend/prisma

FROM base
WORKDIR /app
COPY --from=builder /prod/backend .
RUN npx prisma generate
EXPOSE 3001
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/utils/seedCheck.js && node dist/server.js"]
